CREATE TABLE IF NOT EXISTS proprietario (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,

    PRIMARY KEY(id),
    CONSTRAINT UQ_PROPRIETARIO_NOME UNIQUE (nome),
    CONSTRAINT UQ_PROPRIETARIO_EMAIL UNIQUE (email),
    CONSTRAINT UQ_PROPRIETARIO_TELEFONE UNIQUE (telefone)
);